server:
  port: 8091
spring:
  application:
    name: minos-config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ilovecaffeein/minos-springcloud.git
          username: shuaixiaofeng@caxins.com
          password: 6578007Shuai
          default-label: main
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8090/eureka/
  instance:
    prefer-ip-address: true