server:
  port: 4444
spring:
  application:
    name: minos-basic-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://10.10.8.227:5433/glloans?characterEncoding=utf8
    username: glloans
    password: RunAq4EpFdNNvbj
    filters: stat,wall,log4j
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    connection-properties: druid.stat.merggSql=ture;druid.stat.slowSqlMillis=5000
eureka:
  client:   #客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://localhost:1111/eureka/
      instance:
        instance-id: minos-basic-service    #在信息列表显示主机名称
        prefer-ip-address: true       #访问的路径变为IP地址
        lease-renewal-interval-in-seconds: 2      #设置心跳的时间间隔（默认30秒）
        lease-expiration-duration-in-seconds: 5   #如果现在超过了5秒的间隔（默认9 0秒）