server:
  port: 3333
spring:
  application:
    name: minos-config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ilovecaffeein/minos-springcloud.git #配置中心地址
          username: shuaixiaofeng@caxins.com
          password: 6578007Shuai
          default-label: main
#服务注册到eureka地址
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:1111/eureka/